[package]
name = "c-style-lang-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tower-lsp = "0.20.0"
tokio = {version="1.46.0", features=["full"]}
log = "0.4.27"
env_logger = "0.11.8"
serde_json = "1.0.140"
serde = "1.0.219"
tree-sitter = "0.25.8"
tree-sitter-c = "0.24.1"
